CREATE TABLE hotels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    brand VARCHAR(100),

    house_number INT,
    street VARCHAR(255),
    city VARCHAR(100),
    country VARCHAR(100),
    post_code VARCHAR(20),

    phone VARCHAR(50),
    email VARCHAR(255),

    check_in VARCHAR(10),
    check_out VARCHAR(10)
);

CREATE TABLE hotel_amenities (
    hotel_id BIGINT NOT NULL,
    amenity VARCHAR(100) NOT NULL,
    CONSTRAINT fk_hotel_amenities_hotel_id FOREIGN KEY (hotel_id) REFERENCES hotels (id) ON DELETE CASCADE
)